### ISSUE TITLE
LSP: Incorrectly assuming some optional properties as always given

### ISSUE THREAD

**Issue by cannorin** [ocaml/ocaml-lsp#85]
Background: I tried to use ocaml-lsp from [autozimu/LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim/) but it failed to initialize with the following error:

```
lsp/src/initialize.ml.SignatureHelpClientCapabilities.signatureInformation_of_yojson:
  the following record elements were undefined: documentationFormat
```

The problem was caused at [the deserialization step](https://github.com/ocaml/ocaml-lsp/blob/master/lsp/src/initialize.ml#L1571). 
According to the [spec](https://microsoft.github.io/language-server-protocol/specification#textDocument_signatureHelp), the property `documentationFormat` is optional, and the said client actually omits that property. But ocaml-lsp requires that to be given, which is against the spec.

Above is the case I encountered, but I can see many other properties which are optional in the spec but treated as required (e.g. `parameterInformation`). In my case fixing `documentationFormat` was enough to get it working, but this may cause similar problems when used from other clients.

**Comment by cannorin** [comment]
By looking at #84, Emacs' lsp-mode seem to be also omitting the `documentationFormat` property. I suspect it is the same kind of problem.

**Comment by cannorin** [comment]
Here is an example of initialization request autozimu/LanguageClient-neovim sends:

```json
{
  "jsonrpc": "2.0",
  "method": "initialize",
  "params": {
    "capabilities": {
      "textDocument": {
        "colorProvider": null,
        "completion": { "completionItem": { "snippetSupport": false } },
        "declaration": { "linkSupport": true },
        "definition": { "linkSupport": true },
        "implementation": { "linkSupport": true },
        "publishDiagnostics": { "relatedInformation": true },
        "signatureHelp": {
          "signatureInformation": {
            "parameterInformation": { "labelOffsetSupport": true }
          }
        },
        "typeDefinition": { "linkSupport": true }
      },
      "workspace": {
        "applyEdit": true,
        "didChangeWatchedFiles": { "dynamicRegistration": true }
      }
    },
    "processId": 266288,
    "rootPath": "/home/alice/codes/work/ocaml-lsp",
    "rootUri": "file:///home/alice/codes/work/ocaml-lsp",
    "trace": "off"
  },
  "id": 1
}
```

**Comment by Gbury** [comment]
I have a similar problem with neovim and vim-lsp, which result in:
```
lsp/src/initialize.ml.FoldingRangeClientCapabilities.t_of_yojson: the following record elements were undefined: rangeLimit
```

For reference the initialization request sent is the following:
```
{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "initialize",
  "params": {
    "rootUri": "file:///home/guigui/build/dolmen",
    "capabilities": {
      "workspace": { "configuration": true, "applyEdit": true },
      "textDocument": {
        "implementation": { "linkSupport": true },
        "documentSymbol": {
          "symbolKind": {
            "valueSet": [
              10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
              26, 1, 2, 3, 4, 5, 6, 7, 8, 9
            ]
          },
          "hierarchicalDocumentSymbolSupport": false
        },
        "semanticHighlightingCapabilities": { "semanticHighlighting": false },
        "codeAction": {
          "codeActionLiteralSupport": {
            "codeActionKind": {
              "valueSet": [
                "", "quickfix", "refactor", "refactor.extract",
                "refactor.inline", "refactor.rewrite", "source",
                "source.organizeImports"
              ]
            }
          },
          "dynamicRegistration": false
        },
        "completion": {
          "completionItem": {
            "snippetSupport": false,
            "documentationFormat": [ "plaintext" ]
          },
          "completionItemKind": {
            "valueSet": [
              10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
              1, 2, 3, 4, 5, 6, 7, 8, 9
            ]
          }
        },
        "foldingRange": { "lineFoldingOnly": true },
        "typeDefinition": { "linkSupport": true },
        "typeHierarchy": false,
        "declaration": { "linkSupport": true },
        "definition": { "linkSupport": true }
      }
    },
    "rootPath": "/home/guigui/build/dolmen",
    "processId": 24431,
    "trace": "off"
  }
}

```

**Comment by rgrinberg** [comment]
Thanks for bringing this to my attention. This should be fixed in master. Please test.

In the future, I hope to generate the types from the spec so bugs like this will be less likely.

**Comment by Gbury** [comment]
@rgrinberg  I still have an issue with `Initialize.FoldingRangeClientCapabilities.rangeLimit`:
```
# 0.00 lsp - error
lsp/src/initialize.ml.FoldingRangeClientCapabilities.t_of_yojson: the following record elements were undefined: rangeLimit
```

**Comment by rgrinberg** [comment]
I’ve pushed another fix to master. Try again please

**Comment by Gbury** [comment]
The problem is fixed, thanks !

**Comment by rgrinberg** [comment]
No problem. We have a long term for fix this on the way :)
