### ISSUE TITLE
ocamllsp: -32603: uncaught exception

### ISSUE THREAD

**Issue by aspeddro** [ocaml/ocaml-lsp#871]
I'm getting this error when opening `dune` files.

Error message:
```
RPC[Error] code_name = InternalError, message = "uncaught exception" data = {
  backtrace = 'Raised at Stdune__Code_error.raise in file "otherlibs/stdune/code_error.ml", line 11, chara
cters 30-62\nCalled from Ocaml_lsp_server__Document.with_pipeline_exn in file "ocaml-lsp-server/src/docume
nt.ml", line 189, characters 13-32\nCalled from Ocaml_lsp_server.signature_help in file "ocaml-lsp-server/
src/ocaml_lsp_server.ml", line 454, characters 4-287\nCalled from Ocaml_lsp_server.on_request.later.(fun)
in file "ocaml-lsp-server/src/ocaml_lsp_server.ml", line 762, characters 24-35\nCalled from Fiber__Schedul
er.exec in file "src/fiber/scheduler.ml", line 69, characters 8-11\nRe-raised at Stdune__Exn.raise_with_ba
cktrace in file "otherlibs/stdune/exn.ml" (inlined), line 36, characters 27-56\nCalled from Stdune__Exn_wi
th_backtrace.reraise in file "otherlibs/stdune/exn_with_backtrace.ml", line 18, characters 33-71\nCalled f
rom Fiber__Scheduler.exec in file "src/fiber/scheduler.ml", line 69, characters 8-11\n',
  exn = '("Document.dune", {})'
}
```

LSP Log:

```
[ERROR][2022-10-12 18:29:59] ...lsp/codelens.lua:225	"codelens"	{  code = -32603,  data = {    backtrace = 'Raised at Stdune__Code_error.raise in file "otherlibs/stdune/code_error.ml", line 11, characters 30-62\nCalled from Ocaml_lsp_server.text_document_lens in file "ocaml-lsp-server/src/ocaml_lsp_server.ml", line 506, characters 8-25\nCalled from Ocaml_lsp_server.on_request.later.(fun) in file "ocaml-lsp-server/src/ocaml_lsp_server.ml", line 762, characters 24-35\nCalled from Fiber__Scheduler.exec in file "src/fiber/scheduler.ml", line 69, characters 8-11\nRe-raised at Stdune__Exn.raise_with_backtrace in file "otherlibs/stdune/exn.ml" (inlined), line 36, characters 27-56\nCalled from Stdune__Exn_with_backtrace.reraise in file "otherlibs/stdune/exn_with_backtrace.ml", line 18, characters 33-71\nCalled from Fiber__Scheduler.exec in file "src/fiber/scheduler.ml", line 69, characters 8-11\n',    exn = '("non merlin document has no kind", {})'  },  message = "uncaught exception",  <metatable> = {    __tostring = <function 1>  }}
```

It seems to be related to requests for `documentHighlight`. When attaching the server, requests are made in the following events: `CusorHoldI` and `CursorHold`.

```lua
local on_attach = function(client, bufnr)
  if client.server_capabilities.documentHighlightProvider then
    local group =
      vim.api.nvim_create_augroup('LSP/documentHighlight', { clear = true })
    vim.api.nvim_create_autocmd({ 'CursorHold', 'CursorHoldI' }, {
      callback = vim.lsp.buf.document_highlight,
      buffer = bufnr,
      group = group,
    })
    vim.api.nvim_create_autocmd('CursorMoved', {
      callback = vim.lsp.buf.clear_references,
      buffer = bufnr,
      group = group,
    })
  end
end
```

When disabling `documentHighlight` requests, Neovim does not report error for `dune` files.

Using 
- Neovim 0.8.0 LSP builtin
- OCaml version 4.14.0
- ocamllsp 1.13.1

**Comment by rgrinberg** [comment]
Should be fixed in the next release.

**Comment by aspeddro** [comment]
Still getting the following error: `ocamllsp: -32603: uncaught exception`

```
ocamllsp --version
1.14.0-1-g138e927
```

Log

```
[ERROR][2022-10-19 12:46:05] ...lsp/codelens.lua:225	"codelens"	{  code = -32603,  data = {    backtrace = 'Raised at Stdune__Code_error.raise in file "otherlibs/stdune/code_error.ml", line 11, characters 30-62\nCalled from Ocaml_lsp_server.text_document_lens in file "ocaml-lsp-server/src/ocaml_lsp_server.ml", line 432, characters 8-25\nCalled from Ocaml_lsp_server.on_request.later.(fun) in file "ocaml-lsp-server/src/ocaml_lsp_server.ml", line 693, characters 24-35\nCalled from Fiber__Scheduler.exec in file "src/fiber/scheduler.ml", line 69, characters 8-11\nRe-raised at Stdune__Exn.raise_with_backtrace in file "otherlibs/stdune/exn.ml" (inlined), line 36, characters 27-56\nCalled from Stdune__Exn_with_backtrace.reraise in file "otherlibs/stdune/exn_with_backtrace.ml", line 18, characters 33-71\nCalled from Fiber__Scheduler.exec in file "src/fiber/scheduler.ml", line 69, characters 8-11\n',    exn = '("non merlin document has no kind", {})'  },  message = "uncaught exception",  <metatable> = {    __tostring = <function 1>  }}
```

**Comment by rgrinberg** [comment]
@aspeddro could you try #884 please?

**Comment by aspeddro** [comment]
Still getting the same error.

LSP Log changed:

```
[WARN][2022-10-20 16:29:08] ...lsp/handlers.lua:487	'failed to poll dune registry. Unix.Unix_error(Unix.ENOENT, "stat", "/run/user/1000/dune/rpc")'
```

**Comment by rgrinberg** [comment]
That's in fact a different error. I'll try and fix it as well.
